env:
    TERM: xterm-256color

window:
    dimensions:
        columns: 120
        lines: 30
    
    padding:
        x: 10
        y: 10
    
    dynamic_padding: true

    title: Alacritty

    class:
        instance: Alacritty
        general: Alacritty
    
    opacity: 0.95

scrolling:
    history: 10000

# Font configuration
font:
    normal:
        family: FiraMono Nerd Font
        style: Regular

    # Point size
    size: 12.0

# Colors (Legacy theme from Windows Terminal)
colors:
    # Default colors
    primary:
        background: "#14191F"
        foreground: "#F8F8F2"
    
    cursor:
        text: CellBackground
        cursor: "#FFFFFF"

    vi_mode_cursor:
        text: CellBackground
        cursor: CellForeground
    
    selection:
        background: "#FFFFFF"
        foreground: CellForeground
    
    normal:
        black: "#000000"
        red: "#FF5555"
        green: "#269685"
        yellow: "#FFB86C"
        blue: "#0049A3"
        magenta: "#6272A4"
        cyan: "#6272A4"
        white: "#AEC2E0"
    
    bright:
        black: "#555555"
        red: "#FF5555"
        green: "#50FA7B"
        yellow: "#FFF361"
        blue: "#4565AD"
        magenta: "#FF79C6"
        cyan: "#8BE9FD"
        white: "#FFFFFF"

selection:
    save_to_clipboard: true

cursor:
    style: Beam

mouse:
    double_click: { threshold: 300 }
    triple_click: { threshold: 300 }

mouse_bindings:
    - { mouse: Middle, action: PasteSelection }
    - { mouse: Right, action: Copy }

key_bindings:
    - { key: V, mods: Control|Shift, action: Paste }
    - { key: C, mods: Control|Shift, action: Copy }
    - { key: Insert, mods: Shift, action: PasteSelection }
    - { key: Key0, mods: Control, action: ResetFontSize }
    - { key: Equals, mods: Control, action: IncreaseFontSize }
    - { key: Minus, mods: Control, action: DecreaseFontSize }