#!/bin/bash

result=$(fd -d 1 -t d --base-directory ~ --search-path ~/www --search-path ~/src -E node_modules -E vendor | fzf)
[ -z $result ] && exit

alacritty --working-directory $result
pkill -f fzfmenu
