#!/bin/bash

declare -A STORE_MAP
INCLUDE=()
STORE=()

JSON_DATA=$(sqlite3 ~/.config/Code/User/globalStorage/state.vscdb "SELECT value FROM ItemTable WHERE key='history.recentlyOpenedPathsList'")
RECENT_FOLDERS=$(echo "$JSON_DATA" | jq -r '.entries[] | .folderUri // .workspace.configPath | select(type == "string" and startswith("file://")) | sub("^file://"; "")')

for folder in $RECENT_FOLDERS; do
  STORE_MAP["$(basename "$folder")"]="$folder"
done

while IFS= read -r line; do INCLUDE+=("$line"); done <$HOME/dotfiles/bookmarks.txt

for i in ${INCLUDE[@]}; do
    P="$HOME/$i"
    for dir in $P/*; do
      if [ -d $dir ]; then
        STORE_MAP["$(basename "$dir")"]="$dir"
      fi
    done
done

STORE_MAP["$(basename "$HOME/dotfiles")"]="$HOME/dotfiles"

RESULT_KEY=$(printf "%s\n" "${!STORE_MAP[@]}" | fzf)
RESULT=${STORE_MAP["$RESULT_KEY"]}

[ -z $RESULT ] && exit

code $RESULT >/dev/null 2>&1
