#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Usage: $0 <device_name> <filesystem_type> <directory_name>"
  exit 1
fi

device_name="$1"
filesystem_type="$2"
directory_name="$3"
mount_point="/home/$USER/mnt"
device="/dev/$device_name"
uuid=$(lsblk $device -o UUID --noheadings)

if grep -q "UUID=$uuid" /etc/fstab; then
  echo "UUID $uuid is already present in /etc/fstab. Exiting."
  exit 1
fi

fstab_entry="UUID=$uuid $mount_point/$directory_name $filesystem_type defaults 0 0"
echo "$fstab_entry"

read -p "Do you want to add this entry to /etc/fstab? (y/N): " response
if [[ "$response" =~ ^[Yy]$ ]]; then
  echo "$fstab_entry" | sudo tee -a /etc/fstab > /dev/null
  echo "Entry added to /etc/fstab."
else
  echo "Operation cancelled by user."
fi
