#!/bin/bash
if [ -z "$OS" ]; then
    OS=$(awk '/^ID=/' /etc/os-release | sed -e 's/ID=//' -e 's/"//g' | tr '[:upper:]' '[:lower:]')
fi

print_color() {
    if [ "$1" = "red" ]; then
        COLOR='\033[31m'
    fi

    if [ "$1" = "green" ]; then
        COLOR='\033[0;32m'
    fi

    COLOR='\033[0m'

    printf "${COLOR}%s${NC}\n" "$2"
}

command_exists() {
    command -v $1 >/dev/null 2>&1
}

is_sudoer() {
    sudo -v >/dev/null 2>&1
}

removePackage() {
    for pkg in "$@"; do
        print_color red "Removing $pkg ..."
        if command_exists $pkg && is_sudoer; then
            case $OS in
            ubuntu | debian)
                sudo apt remove -y "$pkg"
                ;;
            centos)
                sudo yum remove -y "$pkg"
                ;;
            arch)
                sudo pacman -Rns --noconfirm "$pkg"
                ;;
            alpine)
                sudo apk del "$pkg"
                ;;
            esac
        fi
    done
}

installPackage() {
    for pkg in "$@"; do
        print_color green "Installing $pkg ..."
        if is_sudoer; then
            case $OS in
            ubuntu | debian)
                sudo apt install -y "$pkg"
                ;;
            centos)
                sudo yum install -y "$pkg"
                ;;
            arch)
                sudo pacman -S --noconfirm "$pkg"
                ;;
            alpine)
                sudo apk add "$pkg"
                ;;
            esac
        fi
    done
}

case "$1" in
i* | inst* | install)
    shift
    installPackage "$@"
    ;;
r* | rm* | rem* | remove)
    shift
    removePackage "$@"
    ;;
h*) cat <<EOF ;;
Usage Example:
    p i/inst/install [package-name]
    p rm/rem/remove [package-name]
EOF
esac
