#!/usr/bin/env bash
set -euo pipefail

XMONAD_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/xmonad"
cd "$XMONAD_DIR"

exec stack ghc \
    --stack-yaml "$XMONAD_DIR/stack.yaml" \
    --package aeson \
    --package bytestring \
    --package containers \
    --package dbus \
    --package directory \
    --package filepath \
    --package text \
    -- \
    --make xmonad.hs \
    -i -ilib \
    -fforce-recomp \
    -main-is main \
    -v0 \
    -outputdir "$HOME/.cache/xmonad/build-$(uname -m)-linux" \
    -o "$1"
