#!/usr/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
xset r rate 300 50 &	# Speed xrate up

setxkbmap -layout gb,ru -model macintosh -option grp:win_space_toggle

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &
