#!/bin/bash

set -euo pipefail

PICOM_TAG="${PICOM_TAG:-v13}"
PREFIX="$HOME/.local"
BUILD_DIR="${TMPDIR:-/tmp}/picom-build-$$"
CONF="$HOME/.config/picom.conf"

installed_version() {
    "$PREFIX/bin/picom" --version 2>/dev/null | head -1 | awk '{print $1}' || true
}

if [ "${FORCE:-false}" != true ] && [ "$(installed_version)" = "$PICOM_TAG" ]; then
    echo "picom $PICOM_TAG already installed at $PREFIX/bin/picom — skipping build"
else
    echo "==> Installing build dependencies (sudo apt)"
    sudo apt-get update -qq
    sudo apt-get install -y --no-install-recommends \
        git meson ninja-build uthash-dev \
        libconfig-dev libdbus-1-dev libegl-dev libev-dev libgl-dev \
        libepoxy-dev libpcre2-dev libpixman-1-dev \
        libx11-xcb-dev libxcb1-dev \
        libxcb-composite0-dev libxcb-damage0-dev libxcb-glx0-dev \
        libxcb-image0-dev libxcb-present-dev libxcb-randr0-dev \
        libxcb-render0-dev libxcb-render-util0-dev libxcb-shape0-dev \
        libxcb-util-dev libxcb-xfixes0-dev

    echo "==> Cloning picom $PICOM_TAG"
    rm -rf "$BUILD_DIR"
    git clone --depth 1 --branch "$PICOM_TAG" https://github.com/yshui/picom.git "$BUILD_DIR"
    trap 'rm -rf "$BUILD_DIR"' EXIT

    echo "==> Building picom (prefix=$PREFIX)"
    cd "$BUILD_DIR"
    meson setup --buildtype=release --prefix="$PREFIX" build
    ninja -C build
    ninja -C build install

    echo "==> Installed: $("$PREFIX/bin/picom" --version | head -1)"
fi

if [ "${KEEP_CONFIG:-false}" = true ]; then
    echo "==> KEEP_CONFIG=true — leaving $CONF untouched"
else
    if [ -f "$CONF" ]; then
        backup="$CONF.bak.$(date +%Y%m%d-%H%M%S)"
        cp "$CONF" "$backup"
        echo "==> Backed up existing config to $backup"
    fi

    echo "==> Writing performance-tuned $CONF"
    cat >"$CONF" <<'EOF'
# Performance-tuned picom config for NVIDIA + xmonad (tiling, no window overlap).
# Generated by inst-picom.sh. Previous config saved as picom.conf.bak.*
#
# Design: vsync for no tearing, no blur/shadows/fade (pure GPU waste on a
# tiling WM), unredir for fullscreen apps, NVIDIA-specific GLX flags.

# ---- Backend ----------------------------------------------------------------
backend = "glx";
vsync = true;

# ---- GLX / NVIDIA tuning ----------------------------------------------------
# Required on NVIDIA proprietary drivers with GLX to avoid artifacts.
xrender-sync-fence = true;
# Only repaint damaged regions.
use-damage = true;

# ---- Unredirect for fullscreen ---------------------------------------------
# Fullscreen apps (browser video, games, mpv) bypass the compositor entirely.
# Biggest idle-GPU win.
unredir-if-possible = true;
unredir-if-possible-delay = 500;
unredir-if-possible-exclude = [ ];

# ---- Effects (disabled for performance) ------------------------------------
# Tiling WMs don't overlap windows, so shadows add GPU cost for zero gain.
shadow = false;
fading = false;
# Blur is the single most expensive effect. Off.
# (No blur-method / blur-kern lines = disabled.)

# ---- Opacity ---------------------------------------------------------------
# Full opacity everywhere — transparency forces per-frame blending on the GPU.
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
inactive-dim = 0.0;

# ---- Corners ---------------------------------------------------------------
# Rounded corners require an extra shader pass per frame. Off.
corner-radius = 0;

# ---- Window type rules -----------------------------------------------------
wintypes:
{
  tooltip      = { fade = false; shadow = false; opacity = 1.0; focus = true; };
  dock         = { shadow = false; };
  dnd          = { shadow = false; };
  popup_menu   = { opacity = 1.0; shadow = false; };
  dropdown_menu = { opacity = 1.0; shadow = false; };
  menu         = { shadow = false; };
  utility      = { shadow = false; };
};

# ---- Misc ------------------------------------------------------------------
detect-rounded-corners = false;
detect-client-opacity  = true;
detect-transient       = true;
detect-client-leader   = true;
use-ewmh-active-win    = true;

log-level = "warn";
EOF
    echo "==> Wrote $CONF"
fi

echo "==> Restarting picom"
pkill -x picom 2>/dev/null || true
sleep 0.3
nohup "$PREFIX/bin/picom" --config "$CONF" >/tmp/picom.log 2>&1 &
disown || true
sleep 0.5

if pgrep -x picom >/dev/null; then
    echo "==> picom running ($("$PREFIX/bin/picom" --version | head -1))"
    echo "==> Sampling GPU load for 5s (expect single-digit %)"
    nvidia-smi pmon -c 5 -s u 2>/dev/null | awk 'NR<=2 || /picom/'
else
    echo "!! picom failed to start — see /tmp/picom.log" >&2
    exit 1
fi
