#!/bin/bash

# Function to set a static IP for eth0 in WSL
set_static_ip() {
    local IP_ADDRESS="$1"
    local INTERFACE="eth0"
    local CIDR="24" # Adjust based on your subnet mask (e.g., 24 for 255.255.255.0)

    if [[ -z "$IP_ADDRESS" ]]; then
        echo "Usage: $0 <IP_ADDRESS>"
        return 1
    fi

    # Backup existing configuration
    if [[ -f /etc/network/interfaces ]]; then
        sudo cp /etc/network/interfaces /etc/network/interfaces.bak-$(date +%F-%H-%M-%S)
    fi

    # Write a new static IP configuration
    cat <<EOF | sudo tee /etc/network/interfaces > /dev/null
# This file is auto-generated by set-static-ip.sh
auto $INTERFACE
iface $INTERFACE inet static
    address $IP_ADDRESS
    netmask 255.255.255.0
EOF

    # Restart the networking service
    sudo ifdown $INTERFACE && sudo ifup $INTERFACE

    echo "Static IP configuration applied for $INTERFACE: $IP_ADDRESS"
}

# Call the function with the provided argument
set_static_ip "$1"

